###############################################################################
#
# Makefile for a script of project 7
#
# Students:
# shaharbirzon, ID 206899049, shahar.birzon@mail.huji.ac.il
# yuval_lev, ID 205734288, yuval.lev@mail.huji.ac.il
#
###############################################################################


all:
	chmod a+x VMtranslator
